from pydantic import BaseModel, Field
from typing import List

# --- PHASE 1 MODELS (Requirements) ---

class AcceptanceCriteria(BaseModel):
    """Specific conditions that a software feature must satisfy to be accepted."""
    id: str = Field(description="A unique identifier for the AC, e.g., AC-1")
    description: str = Field(description="Clear, testable description of the condition")
    expected_behavior: str = Field(description="What the system should do if the condition is met")

class UserStory(BaseModel):
    """A single user story representing a piece of functionality."""
    title: str = Field(description="Short title of the feature")
    as_a: str = Field(description="The user persona (e.g., 'As a regular user')")
    i_want_to: str = Field(description="The action the user wants to perform")
    so_that: str = Field(description="The benefit or value of the action")
    acceptance_criteria: List[AcceptanceCriteria] = Field(description="List of acceptance criteria for this story")

class RequirementsDocument(BaseModel):
    """The final structured output from the Requirements Agent."""
    project_title: str = Field(description="Inferred title of the project/feature")
    overview: str = Field(description="Brief summary of what is being built")
    user_stories: List[UserStory] = Field(description="All user stories required to build the feature")

# --- PHASE 2 MODELS (Design & Execution) ---

class FileBlueprint(BaseModel):
    """A blueprint for a single file to be generated."""
    file_name: str = Field(description="Name of the file with extension, e.g., 'validator.py', 'app.js', 'index.html'")
    purpose: str = Field(description="What this file is responsible for")
    dependencies: List[str] = Field(description="List of standard libraries or packages needed (e.g., 're', 'express', 'lodash')")
    pseudocode: str = Field(description="Rough logical sketch of the functions/classes inside")

class SystemDesignBlueprint(BaseModel):
    """The final structured output from the Design Agent."""
    architecture_overview: str = Field(description="High level explanation of the design choice")
    tech_stack: List[str] = Field(description="The selected languages and frameworks (e.g., ['HTML', 'CSS', 'JavaScript'] or ['Python', 'pytest'])")
    docker_image: str = Field(description="The Docker image to use (e.g., 'node:20-alpine', 'python:3.11-slim')")
    dev_server_command: str = Field(description="Command to start the dev server, bound to 0.0.0.0 (e.g., 'npm run dev -- --host 0.0.0.0', 'python -m http.server 8080 --bind 0.0.0.0'). Set to 'NONE' if no server needed.")
    dev_server_port: int = Field(description="The internal port the dev server binds to (e.g., 5173, 3000, 8080). Set to 0 if none.")
    run_tests_command: str = Field(description="Terminal command to run tests (e.g., 'npm install && npm test' or 'pytest'). Must not be skipped.")
    files: List[FileBlueprint] = Field(description="List of all files that need to be coded")

# --- PHASE 2b MODELS (Code Generation & Execution) ---

class CodeFile(BaseModel):
    """A single generated code file."""
    file_name: str = Field(description="Name of the file with extension, e.g., 'validator.py'")
    source_code: str = Field(description="The complete, runnable source code for this file")

class GeneratedCodeBase(BaseModel):
    """The complete codebase generated by the CodeGen Agent."""
    files: List[CodeFile] = Field(description="List of all generated source code files")

class ExecutionResult(BaseModel):
    """The result of running the test suite in the local sandbox."""
    success: bool = Field(description="True if tests passed, False otherwise")
    logs: str = Field(description="Combined stdout and stderr from the test execution")

# --- PHASE 3 MODELS (Arbitration & Critique) ---

class CriticFeedback(BaseModel):
    """Standardized feedback from a critic agent."""
    critic_name: str = Field(description="Name of the critic (e.g., 'Correctness Critic')")
    severity_score: int = Field(description="Score from 0 (perfect) to 10 (critical failure)")
    issues_list: List[str] = Field(description="List of specific issues found")
    overall_comments: str = Field(description="Summary of the evaluation")

# --- PHASE 3b MODELS (Adjudication) ---

class AdjudicatorDecision(BaseModel):
    """The final decision made by the Adjudicator agent based on all critiques."""
    verdict: str = Field(description="Strictly 'pass', 'revise', or 'error'")
    revision_plan: str = Field(description="Detailed instructions for the CodeGen agent if verdict is 'revise'. If 'error', describes the system failure. If 'pass', a brief approval message.")

# --- PHASE 0 MODELS (Component Decomposition) ---

class ComponentSpec(BaseModel):
    """A single decomposed component from the Master Architect."""
    component_id: str = Field(description="Unique kebab-case identifier, e.g., 'auth-system', 'product-catalog'")
    component_name: str = Field(description="Human-readable name, e.g., 'User Authentication System'")
    description: str = Field(description="What this component does and its scope boundaries")
    scoped_requirements: str = Field(description="Focused requirements text for this component only, containing enough detail for the Design Agent to independently produce a complete blueprint")
    dependencies_on: List[str] = Field(description="IDs of components this depends on (empty list if none). Used for pipeline ordering.")
    priority_order: int = Field(description="Pipeline execution order (1 = first). Components with no dependencies should have lower numbers.")

class ComponentDecomposition(BaseModel):
    """Output of the Master Architect Agent."""
    is_complex: bool = Field(description="If False, the product is simple enough for the single-pass pipeline. If True, decompose into components.")
    project_overview: str = Field(description="High-level product vision describing the overall system")
    shared_tech_stack: List[str] = Field(description="Common tech stack that all components must use (e.g., ['HTML', 'CSS', 'JavaScript', 'Node.js'])")
    shared_docker_image: str = Field(description="Base Docker image all components should use (e.g., 'node:20-alpine')")
    components: List[ComponentSpec] = Field(description="The decomposed component list. Empty if is_complex is False.")
    integration_strategy: str = Field(description="How to merge components: describes routing, shared state, navigation, and cross-component wiring approach")

class ComponentResult(BaseModel):
    """The fully tested output of a single component after passing Critics."""
    component_id: str = Field(description="The component_id this result belongs to")
    component_name: str = Field(description="Human-readable component name")
    blueprint: SystemDesignBlueprint = Field(description="The design blueprint used for this component")
    codebase: GeneratedCodeBase = Field(description="The tested and approved source code for this component")
    execution_result: ExecutionResult = Field(description="The passing test execution result")
