import sys
import json
import re
from pydantic import BaseModel, Field, model_validator, field_validator
from typing import List, Optional, Any

# Ensure singleton module registration across both 'models' and 'backend.models'
if __name__ in ("models", "backend.models") and __name__ in sys.modules:
    sys.modules.setdefault("models", sys.modules[__name__])
    sys.modules.setdefault("backend.models", sys.modules[__name__])


# --- PHASE 1 MODELS (Requirements) ---

class AcceptanceCriteria(BaseModel):
    """Specific conditions that a software feature must satisfy to be accepted."""
    id: str = Field(description="A unique identifier for the AC, e.g., AC-1")
    description: str = Field(description="Clear, testable description of the condition")
    expected_behavior: str = Field(description="What the system should do if the condition is met")

class UserStory(BaseModel):
    """A single user story representing a piece of functionality."""
    title: str = Field(description="Short title of the feature")
    as_a: str = Field(description="The user persona (e.g., 'As a regular user')")
    i_want_to: str = Field(description="The action the user wants to perform")
    so_that: str = Field(description="The business value or benefit")
    acceptance_criteria: List[AcceptanceCriteria] = Field(description="Acceptance criteria for this story")

class RequirementsDocument(BaseModel):
    """The final structured output from the Requirements Agent."""
    project_title: str = Field(description="Inferred title of the project/feature")
    overview: str = Field(description="Brief summary of what is being built")
    user_stories: List[UserStory] = Field(description="All user stories required to build the feature")

# --- PHASE 2 MODELS (Design & Execution) ---

class FileBlueprint(BaseModel):
    """A blueprint for a single file to be generated."""
    file_name: str = Field(description="Name of the file with extension, e.g., 'validator.py', 'app.js', 'index.html'")
    purpose: str = Field(description="What this file is responsible for")
    dependencies: List[str] = Field(description="List of standard libraries or packages needed (e.g., 're', 'express', 'lodash')")
    pseudocode: str = Field(description="Rough logical sketch of the functions/classes inside")

class SystemDesignBlueprint(BaseModel):
    """The final structured output from the Design Agent."""
    architecture_overview: str = Field(description="High level explanation of the design choice")
    tech_stack: List[str] = Field(description="The selected languages and frameworks (e.g., ['HTML', 'CSS', 'JavaScript'] or ['Python', 'pytest'])")
    docker_image: str = Field(description="The Docker image to use (e.g., 'node:20-alpine', 'python:3.11-slim')")
    dev_server_command: str = Field(description="Command to start the dev server, bound to 0.0.0.0 (e.g., 'npm run dev -- --host 0.0.0.0' for Vite port 5173, 'npx --yes serve -p 8080 -H 0.0.0.0' for Node static HTML, or 'python3 -m http.server 8080 --bind 0.0.0.0' strictly for Python images). Must be strictly compatible with docker_image. Set to 'NONE' if no server needed.")
    dev_server_port: int = Field(description="The internal port the dev server binds to (e.g., 5173, 3000, 8080). Set to 0 if none.")
    run_tests_command: str = Field(description="Terminal command to run tests (e.g., 'npm install && npm test' or 'pytest'). Must not be skipped.")
    files: List[FileBlueprint] = Field(description="List of all files that need to be coded")

# --- PHASE 2b MODELS (Code Generation & Execution) ---

class CodeFile(BaseModel):
    """A single generated code file."""
    file_name: str = Field(description="Name of the file with extension, e.g., 'validator.py'")
    source_code: str = Field(description="The complete, runnable source code for this file")

class GeneratedCodeBase(BaseModel):
    """The complete codebase generated by the CodeGen Agent."""
    files: List[CodeFile] = Field(description="List of all generated source code files")

class ExecutionResult(BaseModel):
    """The result of running the test suite in the local sandbox."""
    success: bool = Field(description="True if tests passed, False otherwise")
    logs: str = Field(description="Combined stdout and stderr from the test execution")

# --- PHASE 3 MODELS (Arbitration & Critique) ---

class CriticFeedback(BaseModel):
    """Standardized feedback from a critic agent."""
    critic_name: str = Field(description="Name of the critic (e.g., 'Correctness Critic')")
    severity_score: int = Field(description="Score from 0 (perfect) to 10 (critical failure)")
    issues_list: List[str] = Field(description="List of specific issues found")
    overall_comments: str = Field(description="Summary of the evaluation")

# --- PHASE 3b MODELS (Adjudication) ---

class AdjudicatorDecision(BaseModel):
    """The final decision made by the Adjudicator agent based on all critiques."""
    verdict: str = Field(description="Strictly 'pass', 'revise', or 'error'")
    revision_plan: str = Field(description="Detailed instructions for the CodeGen agent if verdict is 'revise'. If 'error', describes the system failure. If 'pass', a brief approval message.")
    weighted_composite: Optional[float] = Field(default=None, description="Weighted composite severity score (Correctness 50%, Architecture 20%, Completeness 30%)")
    delta: Optional[float] = Field(default=None, description="Score delta (improvement) compared to previous revision")
    dynamic_budget: Optional[int] = Field(default=None, description="Dynamic revision budget calculated as min(5, ceil(composite / 3))")
    early_stop: Optional[bool] = Field(default=False, description="True if early stop triggered due to delta <= 1")

# --- PHASE 0 MODELS (Component Decomposition) ---

class ComponentSpec(BaseModel):
    """A single decomposed component from the Master Architect."""
    component_id: str = Field(description="Unique kebab-case identifier, e.g., 'auth-system', 'product-catalog'")
    component_name: str = Field(description="Human-readable name, e.g., 'User Authentication System'")
    description: str = Field(description="What this component does and its scope boundaries")
    scoped_requirements: str = Field(description="Focused requirements text for this component only, containing enough detail for the Design Agent to independently produce a complete blueprint")
    dependencies_on: List[str] = Field(default_factory=list, description="IDs of components this depends on (empty list if none). Used for pipeline ordering.")
    priority_order: int = Field(description="Pipeline execution order (1 = first). Components with no dependencies should have lower numbers.")
    docker_image: Optional[str] = Field(default=None, description="Optional Docker image override for this specific component (e.g. 'python:3.11-slim' or 'mcr.microsoft.com/playwright:v1.48.0-jammy'). If omitted or null, falls back to shared_docker_image.")
    tech_stack: Optional[List[str]] = Field(default=None, description="Optional tech stack override for this specific component (e.g. ['Python', 'FastAPI', 'pytest']). If omitted or null, falls back to shared_tech_stack.")

    @field_validator("component_id", mode="before")
    @classmethod
    def validate_component_id(cls, v: Any) -> str:
        if v is None or not str(v).strip():
            raise ValueError("component_id must be a non-empty string")
        return str(v).strip()

    @field_validator("docker_image", mode="before")
    @classmethod
    def normalize_docker_image(cls, v: Any) -> Optional[str]:
        if v is None:
            return None
        s = str(v).strip()
        return s if s else None

    @field_validator("dependencies_on", mode="before")
    @classmethod
    def normalize_dependencies_on(cls, v: Any) -> List[str]:
        if v is None:
            return []
        if isinstance(v, str):
            items = [s.strip() for s in v.split(",") if s.strip()]
            return list(dict.fromkeys(items))
        if isinstance(v, (list, tuple, set)):
            items = [str(s).strip() for s in v if str(s).strip()]
            return list(dict.fromkeys(items))
        return list(v)

    @field_validator("tech_stack", mode="before")
    @classmethod
    def normalize_tech_stack(cls, v: Any) -> Optional[List[str]]:
        if v is None:
            return None
        if isinstance(v, str):
            parts = [s.strip() for s in v.split(",") if s.strip()]
            return parts if parts else None
        if isinstance(v, (list, tuple, set)):
            cleaned = [str(s).strip() for s in v if str(s).strip()]
            return cleaned if cleaned else None
        return list(v)

class ComponentDecomposition(BaseModel):
    """Output of the Master Architect Agent."""
    is_complex: bool = Field(description="If False, the product is simple enough for the single-pass pipeline. If True, decompose into components.")
    project_overview: str = Field(description="High-level product vision describing the overall system")
    shared_tech_stack: List[str] = Field(description="Common tech stack that all components must use (e.g., ['HTML', 'CSS', 'JavaScript', 'Node.js'])")
    shared_docker_image: str = Field(description="Base Docker image all components should use (e.g., 'node:20-alpine')")
    components: List[ComponentSpec] = Field(default_factory=list, description="The decomposed component list. Empty if is_complex is False.")
    integration_strategy: str = Field(description="How to merge components: describes routing, shared state, navigation, and cross-component wiring approach")

    @field_validator("components", mode="before")
    @classmethod
    def normalize_components(cls, v: Any) -> List[Any]:
        if v is None:
            return []
        return v

    @field_validator("shared_docker_image", mode="before")
    @classmethod
    def normalize_shared_docker_image(cls, v: Any) -> str:
        if v is None:
            return ""
        return str(v).strip()

    @field_validator("shared_tech_stack", mode="before")
    @classmethod
    def normalize_shared_tech_stack(cls, v: Any) -> List[str]:
        if v is None:
            return []
        if isinstance(v, str):
            return [s.strip() for s in v.split(",") if s.strip()]
        if isinstance(v, (list, tuple, set)):
            return [str(s).strip() for s in v if str(s).strip()]
        return list(v)

def validate_decomposition(decomposition: Any, requirements: Optional[Any] = None) -> ComponentDecomposition:
    """
    Post-LLM validation guard that enforces >= 3 components for complex projects.
    Raises ValueError if is_complex is True and len(components) < 3.
    Also validates JSON strings with surrounding markdown prose, __USAGE__ tokens,
    error objects, component uniqueness, DAG acyclicity, and requirements complexity alignment.
    """
    decomp = None
    if isinstance(decomposition, str):
        text = decomposition.strip()
        if "__RESET__" in text:
            text = text.split("__RESET__")[-1].strip()
        if "__USAGE__" in text:
            text = text.split("__USAGE__")[0].strip()

        # Extract JSON from markdown fences (case-insensitive) if present
        fence_matches = re.findall(r"```(?:json)?\s*(\{[\s\S]*?\})\s*```", text, re.IGNORECASE)
        candidate_texts = []
        if fence_matches:
            # Prioritize candidates containing "is_complex"
            for m in reversed(fence_matches):
                if "is_complex" in m:
                    candidate_texts.insert(0, m.strip())
                else:
                    candidate_texts.append(m.strip())
        else:
            candidate_text = text
            if "```json" in candidate_text.lower():
                idx = candidate_text.lower().find("```json")
                candidate_text = candidate_text[idx + 7:]
                if "```" in candidate_text:
                    candidate_text = candidate_text.split("```", 1)[0]
            elif "```" in candidate_text:
                candidate_text = candidate_text.split("```", 1)[1]
                if "```" in candidate_text:
                    candidate_text = candidate_text.split("```", 1)[0]
            candidate_texts.append(candidate_text.strip())

        data = None
        for cand in candidate_texts:
            # 1. Direct JSON parse
            try:
                parsed = json.loads(cand)
                if isinstance(parsed, dict) and ("is_complex" in parsed or "error" in parsed):
                    data = parsed
                    break
            except Exception:
                pass

            # 2. Slice outermost braces
            first_brace = cand.find("{")
            last_brace = cand.rfind("}")
            if first_brace != -1 and last_brace != -1 and last_brace > first_brace:
                sliced = cand[first_brace:last_brace + 1]
                try:
                    parsed = json.loads(sliced)
                    if isinstance(parsed, dict) and ("is_complex" in parsed or "error" in parsed):
                        data = parsed
                        break
                except Exception:
                    pass

                # 3. Trailing comma cleanup
                cleaned = re.sub(r',\s*([\]}])', r'\1', sliced)
                try:
                    parsed = json.loads(cleaned)
                    if isinstance(parsed, dict) and ("is_complex" in parsed or "error" in parsed):
                        data = parsed
                        break
                except Exception:
                    pass

                # 4. AST literal eval (for Python dict with single quotes / True / False)
                try:
                    import ast
                    evaluated = ast.literal_eval(sliced)
                    if isinstance(evaluated, dict) and ("is_complex" in evaluated or "error" in evaluated):
                        data = evaluated
                        break
                except Exception:
                    pass

        if isinstance(data, dict):
            if "error" in data:
                raise ValueError(f"Decomposition validation failed: {data['error']}")
            if not data.get("is_complex") and data.get("components") is None:
                data["components"] = []
            try:
                decomp = ComponentDecomposition.model_validate(data)
            except Exception as e:
                raise ValueError(f"Decomposition validation failed: {e}")
        elif candidate_texts:
            try:
                decomp = ComponentDecomposition.model_validate_json(candidate_texts[0])
            except Exception as e:
                raise ValueError(f"Decomposition validation failed: {e}")
        else:
            try:
                decomp = ComponentDecomposition.model_validate_json(candidate_text)
            except Exception as e:
                raise ValueError(f"Decomposition validation failed: {e}")

    elif isinstance(decomposition, dict):
        if "error" in decomposition:
            raise ValueError(f"Decomposition validation failed: {decomposition['error']}")
        if not decomposition.get("is_complex") and decomposition.get("components") is None:
            decomposition["components"] = []
        try:
            decomp = ComponentDecomposition.model_validate(decomposition)
        except Exception as e:
            raise ValueError(f"Decomposition validation failed: {e}")
    elif isinstance(decomposition, ComponentDecomposition):
        decomp = decomposition
    else:
        raise ValueError(f"Expected ComponentDecomposition, dict, or JSON string, got {type(decomposition)}")

    # 1. Complexity vs Component count rule (>= 3 components for complex projects)
    if decomp.is_complex and len(decomp.components) < 3:
        raise ValueError(
            f"Decomposition validation failed: Complex projects must have at least 3 components, but got {len(decomp.components)}."
        )

    # 2. Simple products must have empty components list
    if not decomp.is_complex and len(decomp.components) > 0:
        raise ValueError(
            f"Decomposition validation failed: Simple products (is_complex=False) must have an empty components list, but got {len(decomp.components)} components."
        )

    # 3. Requirements complexity alignment rule (handles dict, RequirementsDocument, and JSON string)
    if requirements:
        stories = None
        if isinstance(requirements, dict):
            stories = requirements.get("user_stories")
        elif isinstance(requirements, str):
            try:
                req_obj = json.loads(requirements)
                if isinstance(req_obj, dict):
                    stories = req_obj.get("user_stories")
            except Exception:
                pass
        else:
            stories = getattr(requirements, "user_stories", None)

        if isinstance(stories, list) and len(stories) >= 3 and not decomp.is_complex:
            raise ValueError(
                f"Decomposition validation failed: Product has {len(stories)} user stories (>= 3) and must be marked is_complex=True with at least 3 components, but got is_complex=False."
            )

    # 4. Component ID uniqueness, validity, and DAG integrity checks
    if decomp.components:
        comp_ids = []
        for c in decomp.components:
            cid = str(c.component_id).strip() if c.component_id else ""
            if not cid:
                raise ValueError(
                    f"Decomposition validation failed: Component '{c.component_name}' has an empty component_id. Each component must have a valid non-empty identifier."
                )
            comp_ids.append(cid)

        seen_ids = set()
        duplicates = []
        for cid in comp_ids:
            if cid in seen_ids and cid not in duplicates:
                duplicates.append(cid)
            seen_ids.add(cid)
        if duplicates:
            raise ValueError(
                f"Decomposition validation failed: Duplicate component_id found: {duplicates}. Each component must have a unique component_id."
            )

        valid_ids = set(comp_ids)
        for c in decomp.components:
            cid = str(c.component_id).strip()
            if cid in c.dependencies_on:
                raise ValueError(
                    f"Decomposition validation failed: Component '{cid}' cannot depend on itself."
                )
            invalid_deps = [dep for dep in c.dependencies_on if dep not in valid_ids]
            if invalid_deps:
                raise ValueError(
                    f"Decomposition validation failed: Component '{cid}' references non-existent dependencies: {invalid_deps}."
                )

        # Cycle detection via DFS
        adj = {c.component_id.strip(): list(c.dependencies_on) for c in decomp.components}
        visited = {}  # 0: unvisited, 1: visiting, 2: visited
        cycle_found = []

        def dfs(node, path):
            visited[node] = 1
            path.append(node)
            for neighbor in adj.get(node, []):
                if visited.get(neighbor, 0) == 1:
                    cycle_path = " -> ".join(path[path.index(neighbor):] + [neighbor])
                    cycle_found.append(cycle_path)
                    return True
                if visited.get(neighbor, 0) == 0:
                    if dfs(neighbor, path):
                        return True
            path.pop()
            visited[node] = 2
            return False

        for node in adj:
            if visited.get(node, 0) == 0:
                if dfs(node, []):
                    raise ValueError(
                        f"Decomposition validation failed: Circular dependency detected in component DAG: {cycle_found[0]}."
                    )

    return decomp


class ComponentResult(BaseModel):
    """The fully tested output of a single component after passing Critics."""
    component_id: str = Field(description="The component_id this result belongs to")
    component_name: str = Field(description="Human-readable component name")
    blueprint: SystemDesignBlueprint = Field(description="The design blueprint used for this component")
    codebase: GeneratedCodeBase = Field(description="The tested and approved source code for this component")
    execution_result: ExecutionResult = Field(description="The passing test execution result")


# --- PHASE 4 MODELS (Post-Completion Final Request Phase) ---

class PostCompletionModifyRequest(BaseModel):
    """Payload for modifying an existing codebase post-pipeline completion."""
    prompt: str = Field(description="The user's refactoring, feature addition, bug fix, or styling instruction")
    codebase: GeneratedCodeBase = Field(description="The current codebase snapshot to be selectively refactored")
    blueprint: Optional[SystemDesignBlueprint] = Field(default=None, description="The system architecture blueprint providing tech stack and verification context")
    run_verification: Optional[bool] = Field(default=True, description="Whether to invoke executor sandbox verification after applying modifications")
    mode: Optional[str] = Field(default="QUICK", description="Generation mode: QUICK or COMPLEX")
    generation_mode: Optional[str] = Field(default=None, description="Alias for mode to maintain backward compatibility")


class PostCompletionQueryRequest(BaseModel):
    """Payload for querying/inspecting an existing codebase post-pipeline completion."""
    prompt: Optional[str] = Field(default=None, description="The user's technical question or explanation query about the codebase")
    query: Optional[str] = Field(default=None, description="Alias for prompt")
    codebase: GeneratedCodeBase = Field(description="The current codebase snapshot to inspect (read-only)")
    blueprint: Optional[SystemDesignBlueprint] = Field(default=None, description="Optional system architecture blueprint for context")
    mode: Optional[str] = Field(default="QUICK", description="Generation mode: QUICK or COMPLEX")
    generation_mode: Optional[str] = Field(default=None, description="Alias for mode")

    @model_validator(mode="before")
    @classmethod
    def resolve_query_or_prompt(cls, data: Any) -> Any:
        if isinstance(data, dict):
            p = data.get("prompt") or data.get("query")
            if p is not None:
                data["prompt"] = str(p)
                data["query"] = str(p)
        return data


class RefactorOutput(BaseModel):
    """Structured response from the RefactorAgent containing ONLY modified or newly created files."""
    summary: str = Field(description="Concise description of changes made and files touched")
    modified_files: List[CodeFile] = Field(description="List of files that were modified or newly created. Untouched files MUST be omitted.")


class PostCompletionModifyResponse(BaseModel):
    """API response returned by POST /api/post-completion/modify."""
    success: bool = Field(description="True if modification and merging succeeded")
    summary: str = Field(description="Summary of the applied changes")
    modified_files: List[str] = Field(description="List of file paths that were modified or created")
    codebase: GeneratedCodeBase = Field(description="The updated, fully-merged codebase")
    execution_result: Optional[ExecutionResult] = Field(default=None, description="Sandbox build/test verification result if run_verification was True")

