from pydantic import BaseModel, Field
from typing import List

# --- PHASE 1 MODELS (Requirements) ---

class AcceptanceCriteria(BaseModel):
    """Specific conditions that a software feature must satisfy to be accepted."""
    id: str = Field(description="A unique identifier for the AC, e.g., AC-1")
    description: str = Field(description="Clear, testable description of the condition")
    expected_behavior: str = Field(description="What the system should do if the condition is met")

class UserStory(BaseModel):
    """A single user story representing a piece of functionality."""
    title: str = Field(description="Short title of the feature")
    as_a: str = Field(description="The user persona (e.g., 'As a regular user')")
    i_want_to: str = Field(description="The action the user wants to perform")
    so_that: str = Field(description="The benefit or value of the action")
    acceptance_criteria: List[AcceptanceCriteria] = Field(description="List of acceptance criteria for this story")

class RequirementsDocument(BaseModel):
    """The final structured output from the Requirements Agent."""
    project_title: str = Field(description="Inferred title of the project/feature")
    overview: str = Field(description="Brief summary of what is being built")
    user_stories: List[UserStory] = Field(description="All user stories required to build the feature")

# --- PHASE 2 MODELS (Design & Execution) ---

class FileBlueprint(BaseModel):
    """A blueprint for a single file to be generated."""
    file_name: str = Field(description="Name of the file with extension, e.g., 'validator.py'")
    purpose: str = Field(description="What this file is responsible for")
    dependencies: List[str] = Field(description="List of standard libraries needed (e.g., 're', 'os')")
    pseudocode: str = Field(description="Rough logical sketch of the functions/classes inside")

class SystemDesignBlueprint(BaseModel):
    """The final structured output from the Design Agent."""
    architecture_overview: str = Field(description="High level explanation of the design choice")
    files: List[FileBlueprint] = Field(description="List of all files that need to be coded")

# --- PHASE 2b MODELS (Code Generation & Execution) ---

class CodeFile(BaseModel):
    """A single generated code file."""
    file_name: str = Field(description="Name of the file with extension, e.g., 'validator.py'")
    source_code: str = Field(description="The complete, runnable source code for this file")

class GeneratedCodeBase(BaseModel):
    """The complete codebase generated by the CodeGen Agent."""
    files: List[CodeFile] = Field(description="List of all generated source code files")

class ExecutionResult(BaseModel):
    """The result of running the test suite in the local sandbox."""
    success: bool = Field(description="True if tests passed, False otherwise")
    logs: str = Field(description="Combined stdout and stderr from the test execution")

# --- PHASE 3 MODELS (Arbitration & Critique) ---

class CriticFeedback(BaseModel):
    """Standardized feedback from a critic agent."""
    critic_name: str = Field(description="Name of the critic (e.g., 'Correctness Critic')")
    severity_score: int = Field(description="Score from 0 (perfect) to 10 (critical failure)")
    issues_list: List[str] = Field(description="List of specific issues found")
    overall_comments: str = Field(description="Summary of the evaluation")

# --- PHASE 3b MODELS (Adjudication) ---

class AdjudicatorDecision(BaseModel):
    """The final decision made by the Adjudicator agent based on all critiques."""
    verdict: str = Field(description="Strictly 'pass' or 'revise'")
    revision_plan: str = Field(description="Detailed instructions for the CodeGen agent if verdict is 'revise'. If 'pass', a brief approval message.")