/**
 * AutoDev Unified TypeScript Domain Model & State Specification
 * Single source of truth for autodev-frontend, matching backend Pydantic models.
 *
 * Authoritative sources:
 * - backend/models.py
 * - backend/main.py
 * - backend/pipeline_api.py
 * - backend/log_stream.py
 * - backend/index.html (StateStore autodev_state_v1)
 */

// =============================================================================
// 1. PHASE 1 MODELS: REQUIREMENTS ANALYSIS
// =============================================================================

/**
 * Specific conditions that a software feature must satisfy to be accepted.
 * Corresponds to backend/models.py:AcceptanceCriteria
 */
export interface AcceptanceCriteria {
  /** Unique identifier for the acceptance criterion, e.g., 'AC-1' */
  id: string;
  /** Clear, testable description of the condition */
  description: string;
  /** What the system should do if the condition is met */
  expected_behavior: string;
}

/**
 * A single user story representing a discrete piece of functionality.
 * Corresponds to backend/models.py:UserStory
 */
export interface UserStory {
  /** Short title of the feature */
  title: string;
  /** The user persona, e.g., 'As a registered user' */
  as_a: string;
  /** The action the user wants to perform */
  i_want_to: string;
  /** The business value or expected benefit */
  so_that: string;
  /** Acceptance criteria required for this story */
  acceptance_criteria: AcceptanceCriteria[];
}

/**
 * Structured requirements document synthesized by the Requirements Agent.
 * Corresponds to backend/models.py:RequirementsDocument
 */
export interface RequirementsDocument {
  /** Inferred title of the project or feature */
  project_title: string;
  /** Brief summary of what is being built */
  overview: string;
  /** All user stories required to build the feature */
  user_stories: UserStory[];
}

// =============================================================================
// 2. PHASE 2 MODELS: SYSTEM DESIGN & EXECUTION BLUEPRINTS
// =============================================================================

/**
 * Blueprint for an individual file to be generated.
 * Corresponds to backend/models.py:FileBlueprint
 */
export interface FileBlueprint {
  /** Name of the file with extension, e.g., 'validator.py', 'app.tsx' */
  file_name: string;
  /** Primary architectural responsibility of this file */
  purpose: string;
  /** List of standard libraries or packages needed, e.g., ['re', 'fastapi'] */
  dependencies: string[];
  /** Rough logical sketch or pseudo-implementation of the functions/classes */
  pseudocode: string;
}

/**
 * Structured system architecture blueprint synthesized by the Design Agent.
 * Corresponds to backend/models.py:SystemDesignBlueprint
 */
export interface SystemDesignBlueprint {
  /** High-level explanation of the chosen architectural design */
  architecture_overview: string;
  /** Selected languages, libraries, and frameworks */
  tech_stack: string[];
  /** Docker image used for sandbox execution and dev server */
  docker_image: string;
  /** Command to start the dev server bound to 0.0.0.0; 'NONE' if no server */
  dev_server_command: string;
  /** Internal port the dev server binds to; 0 if none */
  dev_server_port: number;
  /** Terminal command to execute tests, e.g., 'pytest' or 'npm run build' */
  run_tests_command: string;
  /** Manifest of all files that need to be coded */
  files: FileBlueprint[];
}

// =============================================================================
// 3. PHASE 2b MODELS: CODE GENERATION & SANDBOX EXECUTION
// =============================================================================

/**
 * A single generated source code file.
 * Corresponds to backend/models.py:CodeFile
 */
export interface CodeFile {
  /** Relative path of the file with extension, e.g., 'src/validator.py' */
  file_name: string;
  /** Complete, runnable UTF-8 source code for this file */
  source_code: string;
  /** Optional file path alias for backward compatibility */
  path?: string;
}

/**
 * Complete codebase generated by the CodeGen Agent or Integrator.
 * Corresponds to backend/models.py:GeneratedCodeBase
 */
export interface GeneratedCodeBase {
  /** List of all source code files in the codebase */
  files: CodeFile[];
}

/**
 * Result of running tests or build verification in the Docker sandbox.
 * Corresponds to backend/models.py:ExecutionResult
 */
export interface ExecutionResult {
  /** True if tests or build passed cleanly (exit code 0), False otherwise */
  success: boolean;
  /** Combined stdout and stderr logs from the execution */
  logs: string;
}

// =============================================================================
// 4. PHASE 3 MODELS: ARBITRATION, CRITIQUES & ADJUDICATION
// =============================================================================

/**
 * Numeric severity score assigned by a critic agent (0 = perfect, 10 = critical failure).
 */
export type CriticScore = number;

/**
 * Dimension breakdown of critic scores.
 */
export interface CriticScoreBreakdown {
  correctness: number;
  architecture?: number;
  completeness?: number;
  composite?: number;
}

/**
 * Standardized qualitative and quantitative feedback from a critic agent.
 * Corresponds to backend/models.py:CriticFeedback
 */
export interface CriticFeedback {
  /** Name of the critic, e.g., 'Correctness Critic', 'Architecture Critic' */
  critic_name: string;
  /** Score from 0 (perfect) to 10 (critical failure) */
  severity_score: CriticScore;
  /** Specific issues and regressions identified */
  issues_list: string[];
  /** Summary evaluation comments */
  overall_comments: string;
}

/**
 * Valid adjudication verdicts.
 */
export type AdjudicatorVerdict = 'pass' | 'revise' | 'error';

/**
 * Final decision made by the Adjudicator agent based on critic feedback.
 * Corresponds to backend/models.py:AdjudicatorDecision
 */
export interface AdjudicatorDecision {
  /** Verdict: strictly 'pass', 'revise', or 'error' */
  verdict: AdjudicatorVerdict;
  /** Actionable revision instructions for CodeGen if 'revise', error description if 'error', approval message if 'pass' */
  revision_plan: string;
  /** Weighted composite severity score (Correctness 50%, Architecture 20%, Completeness 30%) */
  weighted_composite?: number | null;
  /** Improvement delta compared to previous revision */
  delta?: number | null;
  /** Dynamic revision budget calculated as min(5, ceil(composite / 3)) */
  dynamic_budget?: number | null;
  /** True if early stop was triggered due to diminishing returns (delta <= 1.0) */
  early_stop?: boolean | null;
}

// =============================================================================
// 5. PHASE 0 MODELS: COMPONENT DECOMPOSITION & MULTI-AGENT DAG
// =============================================================================

/**
 * Specification for a decomposed component node in the DAG.
 * Corresponds to backend/models.py:ComponentSpec
 */
export interface ComponentSpec {
  /** Unique kebab-case identifier, e.g., 'auth-system', 'data-pipeline' */
  component_id: string;
  /** Human-readable title, e.g., 'User Authentication System' */
  component_name: string;
  /** Functional scope boundaries and responsibilities */
  description: string;
  /** Focused requirements text scoped strictly to this component */
  scoped_requirements: string;
  /** IDs of upstream components this component depends on */
  dependencies_on: string[];
  /** Execution priority order (1 = first) */
  priority_order: number;
  /** Optional Docker image override for this specific component */
  docker_image?: string | null;
  /** Optional tech stack override for this specific component */
  tech_stack?: string[] | null;
}

/**
 * Master Architect Agent output decomposing projects into multi-component DAGs.
 * Corresponds to backend/models.py:ComponentDecomposition
 */
export interface ComponentDecomposition {
  /** False for single-pass pipeline; True for multi-component DAG */
  is_complex: boolean;
  /** High-level product vision describing the overall system */
  project_overview: string;
  /** Common tech stack used across components */
  shared_tech_stack: string[];
  /** Base Docker image used across components */
  shared_docker_image: string;
  /** Decomposed component list; must have >= 3 components if is_complex is True */
  components: ComponentSpec[];
  /** Cross-component routing, shared state, navigation, and integration strategy */
  integration_strategy: string;
}

/**
 * Fully tested and critic-approved output of a single component.
 * Corresponds to backend/models.py:ComponentResult
 */
export interface ComponentResult {
  /** The component_id this result belongs to */
  component_id: string;
  /** Human-readable component name */
  component_name: string;
  /** Design blueprint used for this component */
  blueprint: SystemDesignBlueprint;
  /** Passing, tested source code for this component */
  codebase: GeneratedCodeBase;
  /** Passing sandbox execution result */
  execution_result: ExecutionResult;
}

// =============================================================================
// 6. PHASE 4 MODELS: POST-COMPLETION & DIFFERENTIAL REVISION
// =============================================================================

/**
 * Payload for requesting surgical modifications to an existing codebase post-completion.
 * Corresponds to backend/models.py:PostCompletionModifyRequest
 */
export interface PostCompletionModifyRequest {
  /** User modification prompt (theming, bug fix, feature addition) */
  prompt: string;
  /** Current codebase snapshot to selectively modify */
  codebase: GeneratedCodeBase;
  /** System blueprint providing tech stack and verification context */
  blueprint?: SystemDesignBlueprint | null;
  /** Whether to invoke executor sandbox verification after applying changes (default: true) */
  run_verification?: boolean;
  /** Active generation mode: 'QUICK' or 'COMPLEX' */
  mode?: AppMode | string;
  /** Alias for mode */
  generation_mode?: AppMode | string | null;
  /** Optional requirements document for arbitration context */
  requirements?: RequirementsDocument | null;
}

/**
 * Payload for read-only conversational inspection of an existing codebase post-completion.
 * Corresponds to backend/models.py:PostCompletionQueryRequest
 */
export interface PostCompletionQueryRequest {
  /** User's technical question or explanation query */
  prompt?: string | null;
  /** Alias for prompt */
  query?: string | null;
  /** Current codebase snapshot to inspect (read-only) */
  codebase: GeneratedCodeBase;
  /** System blueprint for context */
  blueprint?: SystemDesignBlueprint | null;
  /** Active generation mode */
  mode?: AppMode | string;
  /** Alias for mode */
  generation_mode?: AppMode | string | null;
}

/**
 * Structured response from the Refactor Agent containing ONLY modified or new files.
 * Corresponds to backend/models.py:RefactorOutput
 */
export interface RefactorOutput {
  /** Concise description of changes made and files touched */
  summary: string;
  /** List of files that were modified or newly created. Untouched files MUST be omitted. */
  modified_files: CodeFile[];
}

/**
 * Response returned by POST /api/post-completion/modify.
 * Corresponds to backend/models.py:PostCompletionModifyResponse
 */
export interface PostCompletionModifyResponse {
  /** True if modification and codebase merging succeeded */
  success: boolean;
  /** Summary of applied changes */
  summary: string;
  /** Relative paths of files that were modified or created */
  modified_files: string[];
  /** Fully merged, updated codebase */
  codebase: GeneratedCodeBase;
  /** Sandbox execution verification result if run_verification was True */
  execution_result?: ExecutionResult | null;
  /** Critic feedback reports (Correctness, Completeness, Architecture) */
  critic_feedbacks?: CriticFeedback[];
  /** Master Adjudicator decision and scoring */
  decision?: AdjudicatorDecision | null;
}

// =============================================================================
// 7. AUXILIARY APPLICATION & PIPELINE CONTROL TYPES
// =============================================================================

/**
 * Master lifecycle status of the AutoDev pipeline.
 */
export type PipelineStatus = 'idle' | 'running' | 'aborted' | 'completed';

/**
 * Discrete in-flight phase marker used for crash recovery and state restoration.
 * Corresponds to backend/index.html:inFlightPhase recovery matrix.
 */
export type InFlightPhase =
  | 'requirements'
  | 'decomposition'
  | 'single_design'
  | 'single_codegen'
  | 'single_execution'
  | 'single_critics'
  | 'component_dag'
  | 'integration'
  | 'documentation'
  | null;

/**
 * Pipeline generation mode toggle.
 */
export type AppMode = 'QUICK' | 'COMPLEX';

/**
 * Cumulative token counts and INR monetary cost tracking.
 * Reference rates: Gemini 1.5 Flash ($0.075 prompt / $0.30 completion per 1M tokens, 84 INR/USD).
 */
export interface SessionUsage {
  /** Total prompt tokens consumed */
  prompt: number;
  /** Total completion / candidate tokens generated */
  completion: number;
  /** Calculated session cost in Indian Rupees (INR) */
  cost: number;
}

/**
 * Token usage sentinel extracted from stream terminator: \n__USAGE__{prompt},{completion}
 */
export interface TokenUsageSentinel {
  promptTokens: number;
  completionTokens: number;
}

/**
 * Formatted token cost breakdown for the header metrics display.
 */
export interface TokenCostBreakdown {
  promptTokens: number;
  completionTokens: number;
  totalTokens: number;
  costUsd: number;
  costInr: number;
  formattedInr: string;
}

/**
 * Semantic severity classification for terminal logs.
 */
export type LogLevel =
  | 'error'
  | 'warning'
  | 'fallback'
  | 'agent'
  | 'success'
  | 'differential'
  | 'system'
  | 'standard';

/**
 * Real-time log message received from SSE /api/logs/stream.
 */
export interface LogMessage {
  /** Unique client-side identifier or sequence number */
  id: string;
  /** Timestamp string, e.g., '2026-09-22 19:30:00' */
  timestamp: string;
  /** Message content with internal newlines unescaped */
  message: string;
  /** Semantic classification driving terminal syntax coloring */
  level: LogLevel;
  /** Raw unparsed SSE line */
  raw: string;
}

// =============================================================================
// 8. DAG PIPELINE SCHEDULER & DISPATCH CONTRACTS
// =============================================================================

/**
 * Ordered stages in the AutoDev multi-agent DAG pipeline.
 * Corresponds to autodev_pipeline/models.py:StageEnum
 */
export type PipelineStage = 'DESIGN' | 'CODEGEN' | 'CRITICS' | 'INTEGRATION' | 'DOCUMENTATION';

/**
 * Formal lifecycle states of an individual component in the DAG.
 * Corresponds to autodev_pipeline/models.py:ComponentStatus
 */
export type ComponentLifecycleStatus =
  | 'CREATED'
  | 'PENDING_DEPS'
  | 'WAITING_DEP'
  | 'READY'
  | 'IN_STAGE'
  | 'STALLED'
  | 'QUARANTINED'
  | 'COMPLETED'
  | 'FAILED';

/**
 * Payload for POST /api/pipeline/init.
 * Corresponds to backend/pipeline_api.py:PipelineInitInput
 */
export interface PipelineInitInput {
  /** List of decomposed component records */
  components: Array<Record<string, any> | ComponentSpec>;
  /** Generation mode override */
  generation_mode?: AppMode | string | null;
  /** Generation mode */
  mode?: AppMode | string | null;
}

/**
 * Response returned by POST /api/pipeline/init.
 */
export interface PipelineInitResponse {
  /** Initialization status, e.g., 'ok' */
  status: string;
  /** Active pipeline mode */
  mode: AppMode | string;
  /** Maximum revisions permitted (2 for QUICK, 3 for COMPLEX) */
  max_revisions: number;
}

/**
 * Component stage assignment dispatched by the DAG scheduler ticker.
 */
export interface PipelineAssignment {
  /** Target component ID */
  component_id: string;
  /** Assigned stage */
  stage: PipelineStage | string;
  /** Scheduling epoch */
  epoch: number;
}

/**
 * Response returned by GET /api/pipeline/tick.
 */
export interface PipelineTickResponse {
  /** Dispatched component stage assignments */
  assignments: PipelineAssignment[];
}

/**
 * Payload for POST /api/pipeline/complete.
 * Corresponds to backend/pipeline_api.py:CompleteStageInput
 */
export interface CompleteStageInput {
  /** Completed component ID */
  component_id: string;
  /** Completed stage */
  stage: PipelineStage | string;
  /** Verdict: 'pass', 'revise', or 'error' */
  verdict?: AdjudicatorVerdict | string;
  /** Actionable revision instructions if verdict is 'revise' */
  revision_plan?: string | null;
  /** Force stage progression bypassing critics */
  force_proceed?: boolean;
  /** Current revision attempt index */
  revision_count?: number | null;
  /** Active generation mode */
  mode?: AppMode | string | null;
  /** Alias for mode */
  generation_mode?: AppMode | string | null;
  /** Dynamic revision budget */
  dynamic_budget?: number | null;
}

/**
 * Response returned by POST /api/pipeline/complete.
 */
export interface CompleteStageResponse {
  /** True if scheduler successfully recorded completion and unblocked dependents */
  success: boolean;
}

// =============================================================================
// 9. API ENDPOINT REQUEST / RESPONSE CONTRACTS
// =============================================================================

/**
 * Payload for POST /api/generate-requirements.
 * Corresponds to backend/main.py:FeatureRequestInput
 */
export interface FeatureRequestInput {
  feature_request: string;
  mode?: AppMode | string;
  generation_mode?: AppMode | string | null;
}

/**
 * Payload for POST /api/parse-requirements and /api/parse-blueprint.
 * Corresponds to backend/main.py:TextUpdateInput
 */
export interface TextUpdateInput {
  text: string;
  mode?: AppMode | string;
  generation_mode?: AppMode | string | null;
}

/**
 * Payload for POST /api/generate-design.
 * Corresponds to backend/main.py:DesignInput
 */
export interface DesignInput {
  requirements: RequirementsDocument;
  component_context?: string | null;
  component_name?: string | null;
  revision_count?: number;
  mode?: AppMode | string;
  generation_mode?: AppMode | string | null;
  component?: ComponentSpec | Record<string, any> | null;
  decomposition?: ComponentDecomposition | Record<string, any> | null;
  docker_image?: string | null;
  tech_stack?: string[] | null;
}

/**
 * Payload for POST /api/generate-code.
 * Corresponds to backend/main.py:CodeGenInput
 */
export interface CodeGenInput {
  requirements: RequirementsDocument;
  blueprint: SystemDesignBlueprint;
  previous_codebase?: GeneratedCodeBase | null;
  revision_plan?: string | null;
  revision_count?: number;
  component_name?: string | null;
  mode?: AppMode | string | null;
  generation_mode?: AppMode | string | null;
}

/**
 * Payload for POST /api/execute-code and /api/preview/start.
 * Corresponds to backend/main.py:ExecuteInput
 */
export interface ExecuteInput {
  codebase: GeneratedCodeBase;
  blueprint: SystemDesignBlueprint;
  mode?: AppMode | string;
  generation_mode?: AppMode | string | null;
  component?: ComponentSpec | Record<string, any> | null;
  decomposition?: ComponentDecomposition | Record<string, any> | null;
  docker_image?: string | null;
  tech_stack?: string[] | null;
}

/**
 * Payload for POST /api/run-critics.
 * Corresponds to backend/main.py:ArbitrationInput
 */
export interface ArbitrationInput {
  requirements: RequirementsDocument;
  blueprint: SystemDesignBlueprint;
  codebase: GeneratedCodeBase;
  execution_result: ExecutionResult;
  master_decomposition?: ComponentDecomposition | null;
  component_name?: string | null;
  component_id?: string | null;
  phase?: string | null;
  stage?: string | null;
  revision_count?: number;
  mode?: AppMode | string | null;
  generation_mode?: AppMode | string | null;
  previous_composite?: number | null;
}

/**
 * Response returned by POST /api/run-critics.
 */
export interface RunCriticsResponse {
  feedbacks: CriticFeedback[];
  decision: AdjudicatorDecision;
  revision_count: number;
}

/**
 * Payload for POST /api/integrate.
 * Corresponds to backend/main.py:IntegrationInput
 */
export interface IntegrationInput {
  requirements: RequirementsDocument;
  decomposition: ComponentDecomposition;
  component_results: ComponentResult[];
  previous_codebase?: GeneratedCodeBase | null;
  revision_plan?: string | null;
  revision_count?: number;
  mode?: AppMode | string | null;
  generation_mode?: AppMode | string | null;
}

/**
 * Payload for POST /api/generate-documentation.
 * Corresponds to backend/main.py:DocumentationInput
 */
export interface DocumentationInput {
  requirements: RequirementsDocument;
  blueprint: SystemDesignBlueprint;
  codebase: GeneratedCodeBase;
  mode?: AppMode | string | null;
  generation_mode?: AppMode | string | null;
}

/**
 * Response returned by POST /api/preview/start.
 */
export interface PreviewStartResponse {
  url: string;
}

// =============================================================================
// 10. REVISION HISTORY & LOCAL STORAGE STATE PERSISTENCE (`autodev_state_v1`)
// =============================================================================

/**
 * Snapshot of a codebase revision retained in revision history.
 */
export interface RevisionHistoryItem {
  revisionNumber: number;
  label: string;
  timestamp: number;
  codebase: GeneratedCodeBase;
  blueprint?: SystemDesignBlueprint | null;
  executionResult?: ExecutionResult | null;
  criticFeedbacks?: CriticFeedback[];
  decision?: AdjudicatorDecision | null;
  compositeScore?: number | null;
  delta?: number | null;
  summary?: string;
  modifiedFiles?: string[];
  isPostCompletion?: boolean;
  postCompletionRevNumber?: number;
}

/**
 * State record tracking an individual single-pass pipeline run.
 */
export interface SinglePassState {
  blueprint: SystemDesignBlueprint | null;
  codebase: GeneratedCodeBase | null;
  executionResult: ExecutionResult | null;
  revisionCount: number;
  revisionPlan: string | null;
  compositeScore: number | null;
  dynamicBudget: number | null;
}

/**
 * Track status and artifacts for an active DAG component.
 */
export interface ComponentTrackState {
  component: ComponentSpec;
  status: ComponentLifecycleStatus;
  currentStage: PipelineStage | null;
  blueprint: SystemDesignBlueprint | null;
  codebase: GeneratedCodeBase | null;
  executionResult: ExecutionResult | null;
  criticFeedbacks: CriticFeedback[];
  adjudicatorDecision: AdjudicatorDecision | null;
  revisionCount: number;
  dynamicBudget: number | null;
}

/**
 * Complete serialized state schema stored under localStorage key `autodev_state_v1`.
 * Corresponds to backend/index.html:getCurrentState()
 */
export interface AutoDevStateV1 {
  version: number;
  timestamp: number;
  pipelineStatus: PipelineStatus;
  inFlightPhase: InFlightPhase;
  currentMode: AppMode;
  featureRequest: string;
  isComponentMode: boolean;
  activeComponentId: string | null;
  activeComponentStage: PipelineStage | string | null;
  requirements: RequirementsDocument | null;
  decomposition: ComponentDecomposition | null;
  componentStates: Record<string, ComponentTrackState | any>;
  componentResults: ComponentResult[];
  singlePass: SinglePassState;
  singlePassCode: GeneratedCodeBase | null;
  integratedCodebase: GeneratedCodeBase | null;
  executionLogs: string;
  revisionHistory: RevisionHistoryItem[];
  integrationRevisionHistory: RevisionHistoryItem[];
  criticEvaluations: CriticFeedback[];
  adjudicatorDecisions: AdjudicatorDecision[];
  sessionUsage: SessionUsage;
  currentBlueprint: SystemDesignBlueprint | null;
  currentCodebase: GeneratedCodeBase | null;
  currentExecutionResult: ExecutionResult | null;
  currentRevisionPlan: string | null;
  currentRevisionCount: number;
  currentCompositeScore: number | null;
  currentDynamicBudget: number | null;
  pipelineActive: boolean;
  pipelineQueue: any[];
  activeRevisionIndex: number;
  activeFileIndex: number;
  integrationRevisionCount: number;
  integrationRevisionPlan: string | null;
  integrationDynamicBudget: number | null;
  lastIntegrationComposite: number | null;
  integrationActiveRevisionIndex: number;
  integrationCriticHistory: any[];
  integrationActiveCriticIndex: number;
  isPreviewOpen?: boolean;
  isPaused?: boolean;
  pausedAtPhase?: InFlightPhase | null;
  pausedAt?: number | null;
  inspectingPhase?: InFlightPhase | null;
  pauseRevisionIndex?: number;
  pauseSnapshot?: PauseSnapshot | null;
  resumeEpoch?: number;
  timelineMetrics?: PipelineTimelineMetrics;
}

/** Snapshot taken at pause time for change detection */
export interface PauseSnapshot {
  requirements: RequirementsDocument | null;
  decomposition: ComponentDecomposition | null;
  blueprint: SystemDesignBlueprint | null;
  codebase: GeneratedCodeBase | null;
  executionResult: ExecutionResult | null;
  criticEvaluations: CriticFeedback[];
  adjudicatorDecisions: AdjudicatorDecision[];
  revisionCount: number;
  /** For component DAG mode: snapshot of component states */
  componentStates: Record<string, any>;
  integratedCodebase: GeneratedCodeBase | null;
  integrationRevisionCount: number;
}

export const SINGLE_PASS_PHASES: InFlightPhase[] = [
  'requirements',
  'decomposition',
  'single_design',
  'single_codegen',
  'single_execution',
  'single_critics',
];

export const COMPONENT_DAG_PHASES: InFlightPhase[] = [
  'requirements',
  'decomposition',
  'component_dag',
  'integration',
];

export interface ModificationDetectionResult {
  /** The earliest phase that was modified */
  earliestModifiedPhase: InFlightPhase | null;

  /** For DAG mode: earliest component id that was modified */
  earliestModifiedComponentId?: string | null;

  /** Target stage for earliest modified component: CRITICS if only code modified, CODEGEN if blueprint modified, DESIGN if requirements/design */
  modifiedComponentTargetStage?: 'DESIGN' | 'CODEGEN' | 'CRITICS';

  /** Subsequent component IDs following earliestModifiedComponentId in chronological development order */
  subsequentComponentIds?: string[];
  
  /** List of all phases that were modified */
  modifiedPhases: InFlightPhase[];

  /** List of all component IDs that were modified */
  modifiedComponents?: string[];
  
  /** 
   * For revision-aware restart: if the user modified code within a 
   * revision context, this is the revision index to restart from.
   * null means restart the entire phase.
   */
  restartFromRevision: number | null;
  
  /** Human-readable description of what changed */
  changeDescription: string;
}

// ============================================================================
// 10. INTENT CLASSIFICATION & CLARIFICATION
// ============================================================================

export type {
  UserIntent,
  ClassifyIntentRequest,
  ClassifyIntentResponse,
  ClarificationState,
} from './api';

// ============================================================================
// 11. TIMELINE METRICS & GANTT EXECUTION LOGGING (MILESTONE 1 / R1)
// ============================================================================

export type PipelinePhaseType =
  | 'requirements'
  | 'decomposition'
  | 'design'
  | 'codegen'
  | 'execution'
  | 'critics'
  | 'integration'
  | 'documentation';

export interface TimelineInterval {
  id: string;
  phase: PipelinePhaseType;
  stageName: string;
  label: string;
  componentId?: string;
  componentName?: string;
  startTime: number;
  endTime: number;
  durationMs: number;
  status: 'completed' | 'passed' | 'revised' | 'failed' | 'in_progress';
  revisionIndex?: number;
  details?: string;
}

export interface PipelineTimelineMetrics {
  pipelineStartTime: number | null;
  pipelineEndTime: number | null;
  totalDurationMs: number;
  intervals: TimelineInterval[];
}

export * from './github';



